production:
  spot:
    baseUrl: https://api.binance.com
    websocketUrl: wss://stream.binance.com
  future:
    baseUrl: https://fapi.binance.com
    websocketUrl: wss://fstream.binance.com

test:
  spot:
    baseUrl: https://testnet.binance.vision
    websocketUrl: wss://stream.testnet.binance.vision
  future:
    baseUrl: https://testnet.binancefuture.com
    websocketUrl: wss://fstream.binancefuture.com

credentials:
  default:
    production:
      apiKey:
      apiSecret:
    test:
      spot:
        apiKey:
        apiSecret:
      future:
        apiKey:
        apiSecret:
